import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Pwa from './pwa';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: './manifest.json',
  icons: {
    apple: './icon_192x192.png',
    icon: './icon_192x192.png',
  },
  themeColor: '#f69435',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* suppressHydrationWarning={true} for pwa //todo check*/}
      <body className={inter.className} suppressHydrationWarning={true}>
        {children}
        <Pwa />
      </body>
    </html>
  );
}
